import type { Metadata } from "next";
import "@/app/globals.css";
import Script from "next/script";
import Navbar from "../components/beranda/navbar";
import Footer from "../components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Poppins:300,400,500,600,700|PT+Serif:400,400i&display=swap"
          rel="stylesheet"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="beranda_assets/canvas/css/bootstrap.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="beranda_assets/canvas/css/style.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="beranda_assets/canvas/css/swiper.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="beranda_assets/canvas/css/dark.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="beranda_assets/canvas/css/font-icons.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="beranda_assets/canvas/css/animate.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="beranda_assets/canvas/css/magnific-popup.css"
          type="text/css"
        />

        <link
          rel="stylesheet"
          href="beranda_assets/canvas/css/custom.css"
          type="text/css"
        />

        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"
        />
        <link
          rel="stylesheet"
          href="beranda_assets/css/myslickstyle.css"
          type="text/css"
        />

        <link
          rel="stylesheet"
          href="/beranda_assets/canvas/css/custom.css"
          type="text/css"
        />

        {/* <!-- slick slider --> */}
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"
        />
        <link rel="stylesheet" href="/css/myslickstyle.css" type="text/css" />
      </head>
      <body className="stretched">
        <div id="wrapper" className="clearfix">
          <Navbar />
          {children}
          <Footer />
        </div>

        <Script src="/canvas_theme/js/jquery.js" strategy="beforeInteractive" />
        <Script
          src="/canvas_theme/js/plugins.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/canvas_theme/js/plugins.infinitescroll.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/canvas_theme/js/functions.js"
          strategy="afterInteractive"
        />

        {/* <!-- slick slider --> */}
        <Script
          type="text/javascript"
          src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"
          strategy="beforeInteractive"
        />

        <Script id="init-owl-carousel" strategy="afterInteractive">
          {`
            var $ = jQuery.noConflict();
            $(window).on('pluginCarouselReady', function() {
              $('#oc-news').owlCarousel({
                items: 1,
                margin: 20,
                dots: false,
                nav: true,
                navText: ['<i class="icon-angle-left"></i>', '<i class="icon-angle-right"></i>'],
                responsive: {
                  0: { items: 1, dots: true },
                  576: { items: 1, dots: true },
                  768: { items: 2, dots: true },
                  992: { items: 2 },
                  1200: { items: 3 }
                }
              });
            });
          `}
        </Script>

        <Script id="init-slick-our-program" strategy="afterInteractive">
          {`
            var $ = jQuery.noConflict();
            $('.our-program-beranda-slick').slick({
              infinite: true,
              slidesToScroll: 1,
              variableWidth: false,
              autoplay: true,
              autoplaySpeed: 5000,
              slidesToShow: 4,
              prevArrow: "<button  class='slick-prev slick-arrow' type='button'><i class='icon-angle-left'></i></button>",
              nextArrow: "<button  class='slick-next slick-arrow' type='button'><i class='icon-angle-right'></i></button>",
              responsive: [{
                  breakpoint: 576,
                  settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    prevArrow: "",
                    nextArrow: "",
                  }
                },
                {
                  breakpoint: 768,
                  settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                    prevArrow: "",
                    nextArrow: "",
                  }
                },
                {
                  breakpoint: 992,
                  settings: {
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    prevArrow: "",
                    nextArrow: "",
                  }
                },
              ]
            });
          `}
        </Script>

        <Script id="init-kerjasama-yg-terjalin" strategy="afterInteractive">
          {`
            var $ = jQuery.noConflict();
            $('.kerjasamaterjalin').slick({
              infinite: true,
              // variableWidth: true,
              autoplay: true,
              autoplaySpeed: 2000,
              slidesToShow: 6,
              slidesToScroll: 1,
              prevArrow: "",
              nextArrow: "",
              responsive: [{
                  breakpoint: 1600,
                  settings: {
                    slidesToShow: 6,
                    slidesToScroll: 1
                  }
                },
                {
                  breakpoint: 1400,
                  settings: {
                    slidesToShow: 5,
                    slidesToScroll: 1
                  }
                },
                {
                  breakpoint: 1200,
                  settings: {
                    slidesToShow: 4,
                    slidesToScroll: 1
                  }
                },
                {
                  breakpoint: 992,
                  settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3
                  }
                },
                {
                  breakpoint: 768,
                  settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                  }
                },
                {
                  breakpoint: 576,
                  settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1
                  }
                }
              ]
            });
          `}
        </Script>
      </body>
    </html>
  );
}
